"""E2E test: in-chat quote card flow.
1. Drive /api/chat to create a Q-XXXXXX (auto-generated by post-processor)
2. Verify reply contains [[quote_card: Q-XXX]] marker (not inline URLs)
3. Verify GET /api/q/<id>/card?session_id=<sid> returns full data
4. Verify POST /api/q/<id>/sign with session_id=<sid> stores signature
5. Verify the same quote then shows signed_at in /api/q/<id>/card
"""
import os, sys, json, types, re, uuid
os.environ["DB_PATH"] = "/tmp/test_quote_card_e2e.db"
os.environ["ANTHROPIC_API_KEY"] = "fake"
os.environ["DEMO_MODE"] = "off"
sys.path.insert(0, "/tmp/lumora-deploy")

# Mock Anthropic
import anthropic as _anthropic_mod
class _Block:
    def __init__(self, type, text=None):
        self.type = type
        if text is not None: self.text = text
class _Usage:
    def __init__(self):
        self.input_tokens = 100; self.output_tokens = 50
        self.cache_creation_input_tokens = 0; self.cache_read_input_tokens = 0
class _Resp:
    def __init__(self, blocks): self.content = blocks; self.stop_reason = "end_turn"; self.usage = _Usage()
SCRIPT = []
class _FM:
    def create(self, **kw):
        if not SCRIPT: return _Resp([_Block("text", text="(empty)")])
        return _Resp([_Block("text", text=SCRIPT.pop(0))])
class _FA:
    def __init__(self, *a, **kw): self.messages = _FM()
_anthropic_mod.Anthropic = _FA

# Force anthropic-primary
import app.ai_router as _ar
_ar._load_cfg = lambda: {"defaults": {"customer": ""}, "keys": {}}

from app import main as _m
from fastapi.testclient import TestClient
client = TestClient(_m.app)

passed = 0; failed = []
def t(name, ok, detail=""):
    global passed
    if ok: passed += 1
    else: failed.append((name, detail))
    print(f"{'PASS' if ok else 'FAIL'}  {name}" + (f"  — {detail}" if detail else ""))

print("="*70)
print("IN-CHAT QUOTE CARD E2E")
print("="*70)

# Step 1: Drive a chat → bot writes "Book now" → server replaces with card
SCRIPT = ["""Got it!

✓ Services: Deep Cleaning, Pest Control
✓ Date & Time: Wed 20 May 2026 at 10:00 AM
✓ Address: JVC 3838
✓ Name: Khaqan
✓ Phone: 0559396459

[Book now ↗]"""]
sid = "card-test-" + uuid.uuid4().hex[:6]
r = client.post("/api/chat", json={
    "session_id": sid, "message": "yes", "phone": "0559396459"
})
j = r.json()
text = j.get("text", "")
qid_m = re.search(r"\[\[\s*quote_card\s*:\s*(Q-[A-Z0-9]{6})\s*\]\]", text)
t("1. /api/chat reply contains [[quote_card: Q-XXX]] marker",
  bool(qid_m), text[:200])
qid = qid_m.group(1) if qid_m else None

# Step 2: Reply does NOT have inline View/Download/Print/Approve URLs
inline_url_count = sum(text.count(s) for s in [
    "[✅ Approve & sign](", "[👁 View quote](", "[📥 Download PDF](",
    "[🖨 Print](", "[💳 Pay online]("])
t("2. Reply has NO inline URL pill buttons (uses card instead)",
  inline_url_count == 0, f"inline_count={inline_url_count}")

# Step 3: Reply has NO Revise marker pre-sign (v1.24.82 — moved into card after sign)
t("3. Reply does NOT have pre-sign Revise marker (now post-sign only)",
  "✏️ Revise" not in text)

if qid:
    # Step 4: GET /api/q/<id>/card?session_id=<sid> returns data
    r = client.get(f"/api/q/{qid}/card?session_id={sid}")
    cj = r.json()
    t("4. GET /api/q/<id>/card returns ok=true",
      cj.get("ok") is True, str(cj.get("error") or ""))
    t("5. card has items array",
      isinstance(cj.get("items"), list) and len(cj["items"]) >= 2,
      str(len(cj.get("items", []))))
    t("6. card has total_aed > 0",
      (cj.get("total_aed") or 0) > 0, str(cj.get("total_aed")))
    t("7. card has view_url, pdf_url, print_url, pay_url",
      all(cj.get(k) for k in ["view_url","pdf_url","print_url","pay_url"]))
    t("8. card initially NOT signed",
      not cj.get("signed_at"))

    # Step 5: GET without session_id → unauthorized
    r = client.get(f"/api/q/{qid}/card")
    cj_unauth = r.json()
    t("9. GET /api/q/<id>/card without session_id → not ok",
      cj_unauth.get("ok") is False)

    # Step 6: GET with WRONG session_id → unauthorized
    r = client.get(f"/api/q/{qid}/card?session_id=wrong-session")
    cj_wrong = r.json()
    t("10. GET /api/q/<id>/card with wrong session_id → not ok",
      cj_wrong.get("ok") is False)

    # Step 7: POST /api/q/<id>/sign with session_id → success
    fake_sig = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQYV2NgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=="
    r = client.post(f"/api/q/{qid}/sign", json={
        "signature_data_url": fake_sig,
        "customer_note": "test sign in chat",
        "session_id": sid,
    })
    sj = r.json()
    t("11. POST /api/q/<id>/sign with session_id → ok",
      sj.get("ok") is True, str(sj.get("error") or ""))
    t("12. signed_at returned",
      bool(sj.get("signed_at")))

    # Step 8: POST sign with WRONG session_id → fail
    r = client.post(f"/api/q/{qid}/sign", json={
        "signature_data_url": fake_sig,
        "session_id": "totally-wrong",
    })
    sj_wrong = r.json()
    t("13. POST /api/q/<id>/sign with wrong session_id → fail",
      sj_wrong.get("ok") is False)

    # Step 9: GET card again → now shows signed_at
    r = client.get(f"/api/q/{qid}/card?session_id={sid}")
    cj2 = r.json()
    t("14. GET card after sign returns signed_at",
      bool(cj2.get("signed_at")))

# Widget code check
print("\n--- Widget code static checks ---")
wjs = open("/tmp/lumora-deploy/web/widget.js").read()
t("15. widget extracts [[quote_card: Q-XXX]]",
  "quote_card" in wjs and "/api/q/" in wjs)
t("16. widget _buildQuoteCard exists",
  "function _buildQuoteCard" in wjs)
t("17. widget _wireSignPad exists",
  "function _wireSignPad" in wjs)
t("18. widget posts to /api/q/<id>/sign",
  "/sign" in wjs and "signature_data_url" in wjs)

wcss = open("/tmp/lumora-deploy/web/widget.css").read()
t("19. widget.css has .us-qcard styles",
  ".us-qcard" in wcss and ".us-qcard-sigpad" in wcss)

# Summary
total = passed + len(failed)
print()
print("="*70)
print(f"RESULT: {passed}/{total}")
print("="*70)
if failed:
    for n, d in failed: print(f"  FAIL: {n}  {d}")
sys.exit(0 if not failed else 1)
