#!/usr/bin/env python3
"""Regenerate brand assets that are known-broken (v1.24.161).

Issues fixed by this script:
1. Mascot speech bubble — current `servia-mascot-1024x1024.png` has garbled
   fake-Arabic glyphs (AI hallucinated Arabic that doesn't say anything).
   This script regenerates WITHOUT a speech bubble.
2. License plates — current `burj-tap.png`, `hero-split.png` show "12345" /
   "UAE 12345" placeholder plates. Regenerated with proper UAE format
   "DXB A 12345" using emirate code.
3. Watch face emoji boxes (□) — `web/img/wf-frames/*.png` and `wf-previews-v3/*.png`
   show tofu boxes where emoji icons should be. Not customer-facing yet, but
   listed below for when the Wear OS gallery launches.

Run from a laptop with internet + an OpenAI API key (Pollinations is blocked
in the Claude sandbox so this can't run there).

Usage:
    OPENAI_API_KEY=sk-...  python3 .scripts/regen-broken-assets.py
    # Optional: --only mascot,plates    (skip watch_faces)
    # Optional: --dry-run                (print prompts, don't call API)

Cost (DALL-E 3 standard): $0.04/image × 24 images ≈ $0.96 for the full set.
"""
from __future__ import annotations
import argparse, base64, json, os, sys, time, urllib.request, urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "web" / "brand"
RECOVERY = ROOT / "web" / "img" / "recovery"
WF_FRAMES = ROOT / "web" / "img" / "wf-frames"
WF_PREVIEWS = ROOT / "web" / "img" / "wf-previews-v3"

MASTER_STYLE = (
    "Photo-realistic editorial advertising photograph, shot on Canon R5 with "
    "RF 35mm f/1.4 lens, golden-hour cinematic lighting, shallow depth of field, "
    "ultra-detailed skin texture, subtle film grain, high dynamic range. "
    "United Arab Emirates setting. Servia brand: yellow #FCD34D + teal #14B8A6. "
    "Do NOT include any text in Arabic — only English where needed, "
    "and only if rendered with real letters (no hallucinated glyphs)."
)

ASSETS = {
    # Mascot — clean version without speech bubble
    "mascot": [
        {
            "out": BRAND / "servia-mascot-1024x1024.png",
            "size": "1024x1024",
            "prompt": (
                "Friendly cartoon mascot character on solid teal #14B8A6 circular "
                "background, yellow smiling round face wearing a clean white headband "
                "(no Arabic text), white tunic with 'SERVIA' wordmark on the chest "
                "in clean sans-serif letters, simple star decorations in background. "
                "Flat vector illustration style. NO speech bubble, NO Arabic text, "
                "NO calligraphy. Just the mascot character centered, with negative "
                "space around it. Brand colors: yellow #FCD34D and teal #14B8A6."
            ),
        },
        {
            "out": BRAND / "servia-mascot-2048x2048.png",
            "size": "2048x2048",  # DALL-E 3 max is 1792x1024 — upscale separately
            "prompt": None,  # generated by upscaling 1024 → 2048 via PIL
        },
    ],
    # NFC recovery hero — proper UAE license plate
    "plates": [
        {
            "out": RECOVERY / "burj-tap.png",
            "size": "1024x1024",
            "prompt": (
                f"{MASTER_STYLE} Split composition: LEFT half — man in business "
                "casual leaning over open car bonnet at sunset, hand pressing an "
                "NFC sticker labelled 'servia' onto the inner panel. Burj Khalifa "
                "silhouette in the misty background. RIGHT half — yellow & teal "
                "Servia-branded tow truck (Isuzu Elf), driver waving from cab, "
                "'servia' wordmark visible on truck door. UAE license plate "
                "format: white plate with 'DXB' code on left in red, '12345' "
                "in black digits (not just '12345' alone). Bottom overlay: "
                "'TAP ONCE. RECOVERY ON THE WAY.' in white bold sans-serif. "
                "Below in smaller text: 'Servia · 18-min response · AED 250'."
            ),
        },
        {
            "out": RECOVERY / "hero-split.png",
            "size": "1024x1024",
            "prompt": (
                f"{MASTER_STYLE} Same composition as burj-tap.png but with a "
                "Land Cruiser instead of sedan, and the man holding a phone "
                "to tap NFC. UAE license plate format: 'DXB A 12345' with "
                "emirate prefix in red, body digits black. Same overlay text."
            ),
        },
    ],
    # Watch faces — placeholder, NOT customer-facing yet. Skip unless --watch-faces
    "watch_faces": [
        # 20 broken watch faces — emoji codepoints replaced with tofu boxes.
        # Two working ones (servia_hours, servia_dial) use inline SVG.
        # Fix: regenerate either with emoji font baked in, OR rebuild with
        # SVG-only buttons via the Wear OS xml renderer (twa/android/wear/res-raw/*.xml).
        # For now this script does NOT regenerate them — recommend switching
        # to xml-driven rendering for the production build.
    ],
}


def openai_image(prompt: str, size: str, *, model: str = "dall-e-3") -> bytes:
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        sys.exit("Missing OPENAI_API_KEY")
    body = json.dumps({
        "model": model, "prompt": prompt, "n": 1, "size": size,
        "response_format": "b64_json", "quality": "standard",
    }).encode()
    req = urllib.request.Request(
        "https://api.openai.com/v1/images/generations",
        data=body,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        data = json.loads(r.read())
    return base64.b64decode(data["data"][0]["b64_json"])


def upscale_2x(src: Path, dst: Path) -> None:
    from PIL import Image
    img = Image.open(src)
    img2 = img.resize((img.width * 2, img.height * 2), Image.LANCZOS)
    img2.save(dst, optimize=True)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="mascot,plates",
                    help="Comma list of asset groups to regenerate")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    groups = [g.strip() for g in args.only.split(",")]
    n_done = 0
    for group in groups:
        if group not in ASSETS:
            print(f"⚠ unknown group: {group}"); continue
        for item in ASSETS[group]:
            out = item["out"]
            print(f"\n→ {out.relative_to(ROOT)} ({item['size']})")
            if args.dry_run:
                print(f"   PROMPT: {item['prompt'][:200] if item['prompt'] else 'upscale'}")
                continue
            if item["prompt"] is None:
                # upscale step (mascot 1024 → 2048)
                src = BRAND / "servia-mascot-1024x1024.png"
                if not src.exists():
                    print(f"   ⚠ skip: source {src} missing"); continue
                upscale_2x(src, out)
                print(f"   ✓ upscaled to {item['size']}")
            else:
                png = openai_image(item["prompt"], item["size"])
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_bytes(png)
                print(f"   ✓ wrote {len(png)//1024} KB")
                time.sleep(2)  # tiny rate-limit buffer
            n_done += 1

    print(f"\nDone — regenerated {n_done} asset(s).")
    print("Next: review each file visually, commit with cache-bump,")
    print("      and let Railway redeploy.")


if __name__ == "__main__":
    main()
